language: node_js
node_js:
  - node

script: cd client && npm ci && npm run build && cd .. && mv ./client/build ./

deploy:
  provider: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: production

cache: npm
