language: node_js
node_js:
  - node

script: cd client && npm ci && npm run build && cd .. && mv ./client/public/* ./

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: production

cache: npm
